{
  "comments": [
    {
      "key": {
        "uuid": "c2943ff7_fd95b2b1",
        "filename": "tools/at_auth_unlock.py",
        "patchSetId": 1
      },
      "lineNbr": 399,
      "author": {
        "id": 1178083
      },
      "writtenOn": "2019-04-12T19:29:39Z",
      "side": 1,
      "message": "Suggest printing a message that digest was cleared so behavior change is obvious to users",
      "range": {
        "startLine": 399,
        "startChar": 6,
        "endLine": 399,
        "endChar": 24
      },
      "revId": "b6e1736854d76bd64a9dec4a2fb0cdb828cdc85d",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "80a8bd45_240167e7",
        "filename": "tools/at_auth_unlock.py",
        "patchSetId": 1
      },
      "lineNbr": 507,
      "author": {
        "id": 1178083
      },
      "writtenOn": "2019-04-12T19:29:39Z",
      "side": 1,
      "message": "Update ret based on success here, in case someone uses this in scripts. This step should be able to succeed if the unlock did, right? Or did you fine situations where the digest couldn\u0027t be cleared. Ideally wouldn\u0027t treat it as best effort.",
      "range": {
        "startLine": 507,
        "startChar": 4,
        "endLine": 507,
        "endChar": 32
      },
      "revId": "b6e1736854d76bd64a9dec4a2fb0cdb828cdc85d",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    }
  ]
}